### ISSUE TITLE
Errors during network interruption

### ISSUE THREAD

**Issue by utensil** [topaxi/pipeline.nvim#10]
Let me begin by saying gh-actions.nvim is a very smooth experience, and it's starting to grow on me, much better compared to the VSCode one (I need to manually expand to the workflow I wish to see and refresh manually).

So the scenarios is that I'm using gh-actions.nvim on my laptop, then every few hours I will move from one place to another, during that I'll collapse my laptop, so the network will be interrupted. And I'll open it when I settle on a new location, the laptop will reconnect to WiFi.

gh-actions.nvim will make network connection attenpts during that period, resulted in multiple red errors and when I resumed in the new location, I have to hit multiple enters to confirm them.

Is there a way to only indicate network interruption on the panel and the workflow status might be behind, and not report them as errors?

<img width="1904" alt="image" src="https://github.com/user-attachments/assets/88bcb731-063b-4c82-8c24-4011ad00d070">

**Comment by topaxi** [comment]
Good point, I'll try to look into it, but I'll be honest, I'm currently not using the plugin too much myself, as my current company is mainly using Gitlab.

I'll be open for any improvement PR, I could imagine it not being that verbose and maybe even stop making requests after encountering the first error (using an exponential backoff or stopping until manual restart or similar).

**Comment by utensil** [comment]
Thanks for your reply. I have also observed a bit more, and it seems the current logic will backoff in the second attempt, so mostly I have only 2 enters to hit.
