### ISSUE TITLE
Trying to access parent directories too hard

### ISSUE THREAD

**Issue by utensil** [topaxi/pipeline.nvim#11]
So when I'm working on a project with Github workflow, gh-actions.nvim will be able to determine the repo and the workflow file and act accordingly.

But if I open a file outside the repo in the same nvim instance, e.g. `~/.zshrc`, gh-actions.nvim seems to be trying to locate workflow file from that file's parent directories, and triggers multiple file access permission requests (which I didn't grant) so I noticed.

**Comment by topaxi** [comment]
Good catch, haven't thought about this use-case, as I usually start a neovim instance per project. I'll try to look into it if I find some time to do so.

Otherwise very happy to accept a PR which addresses this.

**Comment by utensil** [comment]
Thanks! Sorry, I'm still not very familiar with nvim plugin development, I'll see if I can figure out something.

**Comment by topaxi** [comment]
There was rework on how this plugins detects github action workflows. I hope this also fixed this issue here. Let me know if this still happens and we reopen this issue.
